package com.xin.sharding.mapper;

import com.xin.sharding.model.ShardingDataSourceInfo;

import java.util.List;

public interface ShardingDataSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_datasource
     *
     * @mbg.generated Tue Oct 09 14:13:02 CST 2018
     */
    int deleteByPrimaryKey(Integer dataSourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_datasource
     *
     * @mbg.generated Tue Oct 09 14:13:02 CST 2018
     */
    int insert(ShardingDataSourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_datasource
     *
     * @mbg.generated Tue Oct 09 14:13:02 CST 2018
     */
    int insertSelective(ShardingDataSourceInfo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_datasource
     *
     * @mbg.generated Tue Oct 09 14:13:02 CST 2018
     */
    ShardingDataSourceInfo selectByPrimaryKey(Integer dataSourceId);

    /**
     * 获取数据源信息
     * @param projectId
     * @return
     */
    List<ShardingDataSourceInfo> selectByProjectId(Integer projectId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_datasource
     *
     * @mbg.generated Tue Oct 09 14:13:02 CST 2018
     */
    int updateByPrimaryKeySelective(ShardingDataSourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_datasource
     *
     * @mbg.generated Tue Oct 09 14:13:02 CST 2018
     */
    int updateByPrimaryKey(ShardingDataSourceInfo record);

    List<ShardingDataSourceInfo> selectAll();
}