package com.xin.sharding.mapper;

import com.xin.sharding.model.ShardingDataBase;

import java.util.List;

public interface ShardingDataBaseMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_database
     *
     * @mbg.generated Tue Oct 09 14:13:02 CST 2018
     */
    int deleteByPrimaryKey(Integer dataBaseId);


    int insert(ShardingDataBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_database
     *
     * @mbg.generated Tue Oct 09 14:13:02 CST 2018
     */
    int insertSelective(ShardingDataBase record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_database
     *
     * @mbg.generated Tue Oct 09 14:13:02 CST 2018
     */
    ShardingDataBase selectByPrimaryKey(Integer dataBaseId);

    List<ShardingDataBase> selectByDataSourceId(Integer dataSourceId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_database
     *
     * @mbg.generated Tue Oct 09 14:13:02 CST 2018
     */
    int updateByPrimaryKeySelective(ShardingDataBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_database
     *
     * @mbg.generated Tue Oct 09 14:13:02 CST 2018
     */
    int updateByPrimaryKey(ShardingDataBase record);


    List<ShardingDataBase> selectAll();
}